// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function DeleteFiles(arg1) {
  return window['go']['main']['App']['DeleteFiles'](arg1);
}

export function ExportResults(arg1) {
  return window['go']['main']['App']['ExportResults'](arg1);
}

export function ListDrives() {
  return window['go']['main']['App']['ListDrives']();
}

export function ListSubDirs(arg1) {
  return window['go']['main']['App']['ListSubDirs'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PauseScan() {
  return window['go']['main']['App']['PauseScan']();
}

export function ResumeScan() {
  return window['go']['main']['App']['ResumeScan']();
}

export function StartScan(arg1) {
  return window['go']['main']['App']['StartScan'](arg1);
}
