// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DeleteFiles(arg1) {
  return window['go']['main']['App']['DeleteFiles'](arg1);
}

export function ExportFromStore() {
  return window['go']['main']['App']['ExportFromStore']();
}

export function ExportResults(arg1) {
  return window['go']['main']['App']['ExportResults'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetGroupsPage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetGroupsPage'](arg1, arg2, arg3, arg4);
}

export function GetGroupsPageByScanID(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetGroupsPageByScanID'](arg1, arg2, arg3, arg4, arg5);
}

export function GetLang() {
  return window['go']['main']['App']['GetLang']();
}

export function GetScanHistory() {
  return window['go']['main']['App']['GetScanHistory']();
}

export function GetScanStats() {
  return window['go']['main']['App']['GetScanStats']();
}

export function GetSpaceAnalysis() {
  return window['go']['main']['App']['GetSpaceAnalysis']();
}

export function ListDrives() {
  return window['go']['main']['App']['ListDrives']();
}

export function ListSubDirs(arg1) {
  return window['go']['main']['App']['ListSubDirs'](arg1);
}

export function LoadScan(arg1) {
  return window['go']['main']['App']['LoadScan'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PauseScan() {
  return window['go']['main']['App']['PauseScan']();
}

export function ResumeScan() {
  return window['go']['main']['App']['ResumeScan']();
}

export function SetLang(arg1) {
  return window['go']['main']['App']['SetLang'](arg1);
}

export function StartScan(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['StartScan'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}
