// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelScan():Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ClearAllCache():Promise<void>;

export function DeleteFiles(arg1:Array<string>,arg2:string):Promise<Array<string>>;

export function ExportFromStore():Promise<string>;

export function ExportResults(arg1:main.ScanResult):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetGroupsPage(arg1:number,arg2:number,arg3:string,arg4:string):Promise<main.GroupPage>;

export function GetGroupsPageByScanID(arg1:number,arg2:number,arg3:number,arg4:string,arg5:string):Promise<main.GroupPage>;

export function GetImagePreviewData(arg1:string):Promise<string>;

export function GetLang():Promise<string>;

export function GetScanHistory():Promise<Array<main.ScanHistoryItem>>;

export function GetScanStats():Promise<main.ScanStats>;

export function GetSpaceAnalysis():Promise<Array<main.SpaceAnalysisItem>>;

export function ListDrives():Promise<Array<string>>;

export function ListSubDirs(arg1:string):Promise<Array<string>>;

export function LoadScan(arg1:number):Promise<main.ScanStats>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function OpenPath(arg1:string):Promise<void>;

export function PauseScan():Promise<void>;

export function ResumeScan():Promise<void>;

export function SetLang(arg1:string):Promise<void>;

export function StartScan(arg1:Array<string>,arg2:number,arg3:Array<string>,arg4:Array<string>,arg5:Array<string>,arg6:boolean,arg7:string,arg8:string,arg9:boolean,arg10:string):Promise<main.ScanResult>;
